##### Importing Dependancies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

#### Data Information

In [2]:
data = pd.read_csv('creditcard.csv')

In [3]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7   
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599  \
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25   
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539  \
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
data.describe()

Time            V1            V2            V3            V4   
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  \
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9   
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  \
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24   
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  \
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount   
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000  \
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [6]:
data.shape

(284807, 31)

In [7]:
#checking for missing data
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

The dataset contains no null values

In [8]:
data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

Imbalanced Data

In [9]:
data.groupby('Class').mean()

Time        V1        V2        V3        V4        V5   
Class                                                                   
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  0.005453  \
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21   
Class                                          ...                       
0      0.002419  0.009637 -0.000987  0.004467  ... -0.000644 -0.001235  \
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28   
Class                                                                         
0     -0.000024  0.000070  0.000182 -0.000072 -0.000089 -0.000295 -0.000131  \
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       88.291022  
1      122.211321  

[2 rows x 30 columns]

In [10]:
not_fraud = data[data['Class'] == 0]
fraud = data[data['Class'] == 1]

In [11]:
print(fraud.shape,not_fraud.shape)

(492, 31) (284315, 31)


In [12]:
not_fraud.describe()

Time             V1             V2             V3   
count  284315.000000  284315.000000  284315.000000  284315.000000  \
mean    94838.202258       0.008258      -0.006271       0.012171   
std     47484.015786       1.929814       1.636146       1.459429   
min         0.000000     -56.407510     -72.715728     -48.325589   
25%     54230.000000      -0.917544      -0.599473      -0.884541   
50%     84711.000000       0.020023       0.064070       0.182158   
75%    139333.000000       1.316218       0.800446       1.028372   
max    172792.000000       2.454930      18.902453       9.382558   

                  V4             V5             V6             V7   
count  284315.000000  284315.000000  284315.000000  284315.000000  \
mean       -0.007860       0.005453       0.002419       0.009637   
std         1.399333       1.356952       1.329913       1.178812   
min        -5.683171    -113.743307     -26.160506     -31.764946   
25%        -0.850077      -0.689398      -0.766847      -0.551442   
50%        -0.022405      -0.053457      -0.273123       0.041138   
75%         0.737624       0.612181       0.399619       0.571019   
max        16.875344      34.801666      73.301626     120.589494   

                  V8             V9  ...            V21            V22   
count  284315.000000  284315.000000  ...  284315.000000  284315.000000  \
mean       -0.000987       0.004467  ...      -0.001235      -0.000024   
std         1.161283       1.089372  ...       0.716743       0.723668   
min       -73.216718      -6.290730  ...     -34.830382     -10.933144   
25%        -0.208633      -0.640412  ...      -0.228509      -0.542403   
50%         0.022041      -0.049964  ...      -0.029821       0.006736   
75%         0.326200       0.598230  ...       0.185626       0.528407   
max        18.709255      15.594995  ...      22.614889      10.503090   

                 V23            V24            V25            V26   
count  284315.000000  284315.000000  284315.000000  284315.000000  \
mean        0.000070       0.000182      -0.000072      -0.000089   
std         0.621541       0.605776       0.520673       0.482241   
min       -44.807735      -2.836627     -10.295397      -2.604551   
25%        -0.161702      -0.354425      -0.317145      -0.327074   
50%        -0.011147       0.041082       0.016417      -0.052227   
75%         0.147522       0.439869       0.350594       0.240671   
max        22.528412       4.584549       7.519589       3.517346   

                 V27            V28         Amount     Class  
count  284315.000000  284315.000000  284315.000000  284315.0  
mean       -0.000295      -0.000131      88.291022       0.0  
std         0.399847       0.329570     250.105092       0.0  
min       -22.565679     -15.430084       0.000000       0.0  
25%        -0.070852      -0.052950       5.650000       0.0  
50%         0.001230       0.011199      22.000000       0.0  
75%         0.090573       0.077962      77.050000       0.0  
max        31.612198      33.847808   25691.160000       0.0  

[8 rows x 31 columns]

In [13]:
fraud.describe()

Time          V1          V2          V3          V4   
count     492.000000  492.000000  492.000000  492.000000  492.000000  \
mean    80746.806911   -4.771948    3.623778   -7.033281    4.542029   
std     47835.365138    6.783687    4.291216    7.110937    2.873318   
min       406.000000  -30.552380   -8.402154  -31.103685   -1.313275   
25%     41241.500000   -6.036063    1.188226   -8.643489    2.373050   
50%     75568.500000   -2.342497    2.717869   -5.075257    4.177147   
75%    128483.000000   -0.419200    4.971257   -2.276185    6.348729   
max    170348.000000    2.132386   22.057729    2.250210   12.114672   

               V5          V6          V7          V8          V9  ...   
count  492.000000  492.000000  492.000000  492.000000  492.000000  ...  \
mean    -3.151225   -1.397737   -5.568731    0.570636   -2.581123  ...   
std      5.372468    1.858124    7.206773    6.797831    2.500896  ...   
min    -22.105532   -6.406267  -43.557242  -41.044261  -13.434066  ...   
25%     -4.792835   -2.501511   -7.965295   -0.195336   -3.872383  ...   
50%     -1.522962   -1.424616   -3.034402    0.621508   -2.208768  ...   
75%      0.214562   -0.413216   -0.945954    1.764879   -0.787850  ...   
max     11.095089    6.474115    5.802537   20.007208    3.353525  ...   

              V21         V22         V23         V24         V25         V26   
count  492.000000  492.000000  492.000000  492.000000  492.000000  492.000000  \
mean     0.713588    0.014049   -0.040308   -0.105130    0.041449    0.051648   
std      3.869304    1.494602    1.579642    0.515577    0.797205    0.471679   
min    -22.797604   -8.887017  -19.254328   -2.028024   -4.781606   -1.152671   
25%      0.041787   -0.533764   -0.342175   -0.436809   -0.314348   -0.259416   
50%      0.592146    0.048434   -0.073135   -0.060795    0.088371    0.004321   
75%      1.244611    0.617474    0.308378    0.285328    0.456515    0.396733   
max     27.202839    8.361985    5.466230    1.091435    2.208209    2.745261   

              V27         V28       Amount  Class  
count  492.000000  492.000000   492.000000  492.0  
mean     0.170575    0.075667   122.211321    1.0  
std      1.376766    0.547291   256.683288    0.0  
min     -7.263482   -1.869290     0.000000    1.0  
25%     -0.020025   -0.108868     1.000000    1.0  
50%      0.394926    0.146344     9.250000    1.0  
75%      0.826029    0.381152   105.890000    1.0  
max      3.052358    1.779364  2125.870000    1.0  

[8 rows x 31 columns]

#### Running a Logistic Regression Model on this data

In [14]:
X = data.drop(columns = 'Class',axis = 1)
y = data['Class']

In [15]:
X.shape

(284807, 30)

In [16]:
X.head()

Time        V1        V2        V3        V4        V5        V6        V7   
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599  \
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V20       V21       V22       V23       V24   
0  0.098698  0.363787  ...  0.251412 -0.018307  0.277838 -0.110474  0.066928  \
1  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...  0.524980  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  
0  0.128539 -0.189115  0.133558 -0.021053  149.62  
1  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3  0.647376 -0.221929  0.062723  0.061458  123.50  
4 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

In [17]:
y.shape

(284807,)

In [18]:
y.nunique()

2

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score,recall_score,f1_score
from sklearn.preprocessing import StandardScaler

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.25, random_state = 1)

In [21]:
print(X_train.shape,X_test.shape,X.shape)

(213605, 30) (71202, 30) (284807, 30)


In [22]:
model = LogisticRegression()

In [23]:
scale = StandardScaler()

In [24]:
X_train_scale = scale.fit_transform(X_train)
X_test_scale = scale.transform(X_test)

In [25]:
model.fit(X_train_scale,y_train)

LogisticRegression()

#### Model Evaluation

In [26]:
y_train_predict = model.predict(X_train_scale)
train_acc = accuracy_score(y_train_predict, y_train)

In [27]:
train_acc

0.9992837246319141

In [28]:
y_test_predict = model.predict(X_test_scale)
test_acc = accuracy_score(y_test_predict, y_test)

In [29]:
test_acc

0.9991573270413753

In [30]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [31]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.8311688311688312
Recall: 0.5765765765765766
F1-Score: 0.6808510638297872


### Data is highly biased, so undersample not_fraud dataset

In [32]:
not_fraud_sample = not_fraud.sample(n = 492)

In [33]:
not_fraud_sample.shape

(492, 31)

In [34]:
sample_data = pd.concat([not_fraud_sample,fraud])

In [35]:
sample_data.head()

Time        V1        V2        V3        V4        V5        V6   
121863   76348.0 -0.693974 -0.090899  2.020552 -2.445105 -1.024347 -1.076181  \
239571  150165.0  2.039614 -0.157515 -1.197560  0.227835 -0.134250 -1.199136   
174268  121844.0 -0.311883 -0.090783 -0.315258 -0.628834  1.335617  4.941917   
147583   88711.0 -0.117687 -0.055244  0.607375 -1.113942  0.337624 -0.058520   
13245    23303.0 -0.377595 -0.197655  2.083405 -0.967993 -1.058481  0.962364   

              V7        V8        V9  ...       V21       V22       V23   
121863 -0.072034 -0.553573 -2.007690  ... -0.233462 -0.320602  0.004495  \
239571  0.140236 -0.376631  0.441868  ...  0.138758  0.474850  0.081452   
174268 -0.947847 -0.649687 -1.312280  ...  1.103685 -1.358198 -0.698145   
147583  0.098427  0.040602 -1.258037  ...  0.005739  0.568897  0.012013   
13245  -0.549479  0.323521  0.802937  ... -0.019989  0.260730 -0.086663   

             V24       V25       V26       V27       V28  Amount  Class  
121863  0.682515 -0.542110 -0.704661 -0.557370 -0.052089    9.80      0  
239571 -0.040593 -0.059083  0.684299 -0.083569 -0.061837   27.81      0  
174268  0.669232  1.468152 -0.232672  0.319056  0.129854  203.00      0  
147583  0.714436 -0.703354 -0.311008  0.251901  0.229868   16.57      0  
13245  -0.356329 -0.166513 -0.298864 -0.042977 -0.016397   76.26      0  

[5 rows x 31 columns]

In [36]:
sample_data.shape

(984, 31)

In [37]:
sample_data['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

#### Running Logistic Regression

In [38]:
X_sample = sample_data.drop(columns = 'Class', axis = 1)
y_sample = sample_data['Class']

In [39]:
print(X_sample.shape,y_sample.shape)

(984, 30) (984,)


In [40]:
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size = 0.25, random_state = 2)

In [41]:
print(X_train.shape, X_test.shape)

(738, 30) (246, 30)


In [42]:
scale = StandardScaler()

In [43]:
X_train_scale = scale.fit_transform(X_train)
X_test_scale = scale.transform(X_test)

In [44]:
model = LogisticRegression()

In [45]:
model.fit(X_train_scale,y_train)

LogisticRegression()

#### Model Eval

In [46]:
y_train_predict = model.predict(X_train_scale)
y_train_acc = accuracy_score(y_train_predict, y_train)
y_train_acc

0.9525745257452575

In [47]:
y_test_predict = model.predict(X_test_scale)
y_test_acc = accuracy_score(y_test_predict, y_test)
y_test_acc

0.9471544715447154

In [48]:
confusion_matrix(y_test,y_test_predict)

array([[111,   2],
       [ 11, 122]], dtype=int64)

In [49]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [50]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.9838709677419355
Recall: 0.9172932330827067
F1-Score: 0.9494163424124513


#### Using Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
model_2 = RandomForestClassifier() 

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 2)

In [54]:
model_2.fit(X_train,y_train)

RandomForestClassifier()

#### Model Evaluation

In [55]:
y_train_predict = model_2.predict(X_train)
y_train_acc = accuracy_score(y_train,y_train_predict)
y_train_acc

1.0

In [56]:
y_test_predict = model_2.predict(X_test)
y_test_acc = accuracy_score(y_test_predict,y_test)
y_test_acc

0.9996629308165501

In [57]:
confusion_matrix(y_test_predict,y_test)

array([[71088,    17],
       [    7,    90]], dtype=int64)

In [58]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [59]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.9278350515463918
Recall: 0.8411214953271028
F1-Score: 0.8823529411764706


#### Random Forest Params with GridSearch

In [60]:
from sklearn.model_selection import GridSearchCV

In [61]:
param_grid = {
    'n_estimators': [50, 100, 150, 200],  
    'max_depth': [None, 10, 20],     
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4] }

In [62]:
model_2 = RandomForestClassifier(random_state = 2)

In [63]:
grid_search = GridSearchCV(estimator = model_2, param_grid = param_grid, cv=3, scoring='accuracy', verbose=1, n_jobs=-1)

In [64]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 108 candidates, totalling 324 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=2), n_jobs=-1,
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 150, 200]},
             scoring='accuracy', verbose=1)

In [65]:
print("Best Parameters:", grid_search.best_params_)
print("Best Training Accuracy:", grid_search.best_score_)

Best Parameters: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
Best Training Accuracy: 0.9995224835481767


In [66]:
best_model = grid_search.best_estimator_

In [67]:
y_train_predict = best_model.predict(X_train)
y_train_acc = accuracy_score(y_train,y_train_predict)
y_train_acc

0.9997986938507993

In [68]:
y_test_predict = best_model.predict(X_test)
y_test_acc = accuracy_score(y_test, y_test_predict)
y_test_acc

0.9996488862672397

In [69]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [70]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.9270833333333334
Recall: 0.8317757009345794
F1-Score: 0.8768472906403941


#### Random Forest with Sampled Data

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size = 0.25, random_state = 2)

In [72]:
model_2.fit(X_train,y_train)

RandomForestClassifier(random_state=2)

In [73]:
y_train_predict = model_2.predict(X_train)
y_train_acc = accuracy_score(y_train,y_train_predict)
y_train_acc

1.0

In [74]:
y_test_predict = model_2.predict(X_test)
y_test_acc = accuracy_score(y_test_predict,y_test)
y_test_acc

0.9390243902439024

In [75]:
confusion_matrix(y_test_predict,y_test)

array([[111,  13],
       [  2, 120]], dtype=int64)

In [76]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [77]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.9836065573770492
Recall: 0.9022556390977443
F1-Score: 0.9411764705882353


#### Random Forest with sampled data and Grid Search Params


In [78]:
param_grid = {
    'n_estimators': [50, 100, 150, 200],  
    'max_depth': [None, 10, 20],     
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4] }

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size = 0.25, random_state = 2)

In [80]:
model_2 = RandomForestClassifier(random_state = 2)

In [81]:
grid_search = GridSearchCV(estimator = model_2, param_grid = param_grid, cv=3, scoring='accuracy', verbose=1, n_jobs=-1)

In [82]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 108 candidates, totalling 324 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=2), n_jobs=-1,
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 150, 200]},
             scoring='accuracy', verbose=1)

In [83]:
print("Best Parameters:", grid_search.best_params_)
print("Best Training Accuracy:", grid_search.best_score_)

Best Parameters: {'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 150}
Best Training Accuracy: 0.9444444444444443


In [84]:
best_model = grid_search.best_estimator_

In [85]:
y_train_predict = best_model.predict(X_train)
y_train_acc = accuracy_score(y_train,y_train_predict)
y_train_acc

0.975609756097561

In [86]:
y_test_predict = best_model.predict(X_test)
y_test_acc = accuracy_score(y_test_predict,y_test)
y_test_acc

0.9390243902439024

In [87]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [88]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.9758064516129032
Recall: 0.9097744360902256
F1-Score: 0.9416342412451362


In [89]:
confusion_matrix(y_test_predict,y_test)

array([[110,  12],
       [  3, 121]], dtype=int64)

#### Using SVM

In [90]:
from sklearn.svm import SVC

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)

In [92]:
model_3 = SVC()

In [93]:
scaler = StandardScaler()

In [94]:
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [95]:
model_3.fit(X_train_scale,y_train)

SVC()

In [96]:
y_train_predict = model_3.predict(X_train_scale)
y_train_acc = accuracy_score(y_train,y_train_predict)
y_train_acc

0.9996488846234873

In [98]:
y_test_predict = model_3.predict(X_test_scale)
y_test_acc = accuracy_score(y_test_predict,y_test)
y_test_acc

0.9994943962248252

In [99]:
confusion_matrix(y_test_predict,y_test)

array([[71089,    30],
       [    6,    77]], dtype=int64)

In [100]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [101]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.927710843373494
Recall: 0.719626168224299
F1-Score: 0.8105263157894735


#### SVM Sampled Data

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X_sample, y_sample, test_size=0.25, random_state=2)

In [103]:
model_3 = SVC()

In [104]:
scaler = StandardScaler()

In [105]:
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [106]:
model_3.fit(X_train_scale,y_train)

SVC()

In [107]:
y_train_predict = model_3.predict(X_train_scale)
y_train_acc = accuracy_score(y_train,y_train_predict)
y_train_acc

0.9512195121951219

In [110]:
y_test_predict = model_3.predict(X_test_scale)
y_test_acc = accuracy_score(y_test_predict,y_test)
y_test_acc

0.9390243902439024

In [111]:
confusion_matrix(y_test_predict,y_test)

array([[111,  13],
       [  2, 120]], dtype=int64)

In [112]:
precision = precision_score(y_test, y_test_predict)
recall = recall_score(y_test, y_test_predict)
f1 = f1_score(y_test, y_test_predict)

In [113]:
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)

Precision: 0.9836065573770492
Recall: 0.9022556390977443
F1-Score: 0.9411764705882353


In [121]:
scores_data = {
    'Model': ['LR (unsampled)', 'LR (sampled)', 'RF (unsampled)', 'RF (unsampled-GS)', 'RF (sampled)', 'RF (sampled-GS)', 'SVM (unsampled)', 'SVM (sampled)'],
    'Precision': [0.83117, 0.96062, 0.92784, 0.99965, 0.98361, 0.99180, 0.92771, 0.983606],
    'Recall': [0.57658, 0.91729, 0.84112, 0.92708, 0.90226, 0.90977, 0.71962, 0.90225],
    'F1 Score': [0.68085, 0.93846, 0.88235, 0.83178, 0.94118, 0.94902, 0.81052, 0.94117],
    'Accuracy': [0.99916, 0.93495, 0.99966, 0.87685, 0.93902, 0.94715, 0.99949, 0.93902]
}

In [122]:
scores_data = pd.DataFrame(scores_data)

In [123]:
scores_data

Model  Precision   Recall  F1 Score  Accuracy
0     LR (unsampled)   0.831170  0.57658   0.68085   0.99916
1       LR (sampled)   0.960620  0.91729   0.93846   0.93495
2     RF (unsampled)   0.927840  0.84112   0.88235   0.99966
3  RF (unsampled-GS)   0.999650  0.92708   0.83178   0.87685
4       RF (sampled)   0.983610  0.90226   0.94118   0.93902
5    RF (sampled-GS)   0.991800  0.90977   0.94902   0.94715
6    SVM (unsampled)   0.927710  0.71962   0.81052   0.99949
7      SVM (sampled)   0.983606  0.90225   0.94117   0.93902

In [124]:
scores_data['Agg Score'] = (scores_data['Precision'] + scores_data['Recall'] + scores_data['F1 Score'] + scores_data['Accuracy']) / 4
best_model_row = scores_data.loc[scores_data['Agg Score'].idxmax()]
print("Best Model:")
print(best_model_row[['Model', 'Precision', 'Recall', 'F1 Score', 'Accuracy', 'Agg Score']])

Best Model:
Model        RF (sampled-GS)
Precision             0.9918
Recall               0.90977
F1 Score             0.94902
Accuracy             0.94715
Agg Score           0.949435
Name: 5, dtype: object


Overall, Random Forest of the sampled data using Grid Search to find the best parameters peformed the best for the given dataset, and it was found that models using the sampled data gave better scores, owing to the imbalanced dataset.